<table style="width:100%; float: center;text-align: center;">
<table style="width:50%; float: left; text-align: center;">
  <tr><td><b>ID:</b> $sampleId$</td></tr>
</table>
<table style="width:50%; float: right; text-align: center;">
  <tr><td><b>Initial height:</b> $sampleIniHeight$</td></tr>
  <tr><td><b>Final height:</b> $sampleFimHeight$</td></tr>
  <tr><td><b>Length:</b> $sampleLength$</td></tr>
  <tr><td><b>Wind angle:</b> $sampleWindAngle$</td></tr>
  <tr><td><b>Wind speed:</b> $sampleWindSpeed$</td></tr>
  <tr><td><b>Max velocity:</b> $sampleMaxVel$</td></tr>
  <tr><td><b>Min velocity:</b> $sampleMinVel$</td></tr>
</table>
</table>



