<html>

<head>
<title>Best path</title>
</head>

<body>
<center><h1>Best path</h1></center>
<ul>
  <li><b>Project name:</b> $projectName$</li>
  <li><b>Analysis name:</b> $sampleName$</li>
  <li><b>Travel time:</b> $sampleTime$</li>
  <li><b>Number of records:</b> $sampleRecords$</li>
  <li><b>Energy Consumption:</b> $energyConsumption$</li>
  <li><b>Toll Cost:</b> $tollCost$</li>
</ul>

<center><h2>Roads:</h2></center>