<!DOCTYPE html>
<html>

<head>
<title>Best path for given conditions</title>
</head>

<body>
<center><h1>$projectName$</h1></center>
<ul>
  <li><b>Analysis name:</b> $sampleName$</li>
  <li><b>Travel time:</b> $sampleTime$</li>
  <li><b>Number of records:</b> $sampleRecords$</li>
</ul>  

<center><h2>best path</h2></center>
<table style="width:100%; float: center;text-align: center;">
  <tr>
  <th><h3><div style="margin-left: 10px; margin-right: 5px;">Segment</div></h3></th>
  <th><h3><div style="margin-left: -15px;">Information</div></h3></th>
  </tr>
</table>


