package lapr.project.ui;

import lapr.project.controller.CreateProjectController;

import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.util.function.Consumer;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Provides user interface components for the creation of a project
 */
public final class CreateProjectUI extends javax.swing.JFrame {

    private static final long serialVersionUID = -1818083907306250629L;
    private CreateProjectController createProjectController;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgLateral;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonRoad;
    private javax.swing.JButton jButtonVehicle;
    private javax.swing.JLabel jLabelPDesc;
    private javax.swing.JLabel jLabelPName;
    private javax.swing.JLabel jLabelPageTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldDescription;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JPanel orangeBorder;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form CreateProjectUI
     */
    private CreateProjectUI() {
        super("Create Project");
        createProjectController = new CreateProjectController(Main.dbCom);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InitializeUIElements initializer = new InitializeUIElements();
        jPanel1 = new javax.swing.JPanel();
        imgLateral = new javax.swing.JLabel();
        orangeBorder = new javax.swing.JPanel();
        jButtonCreate = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jTextFieldName = new javax.swing.JTextField();
        jLabelPageTitle = new javax.swing.JLabel();
        jLabelPName = new javax.swing.JLabel();
        jTextFieldDescription = new javax.swing.JTextField();
        jLabelPDesc = new javax.swing.JLabel();
        jButtonRoad = new javax.swing.JButton();
        jButtonVehicle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(45, 46, 45));

        imgLateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fundo.png"))); // NOI18N

        orangeBorder.setBackground(new java.awt.Color(250, 152, 60));

        javax.swing.GroupLayout orangeBorderLayout = new javax.swing.GroupLayout(orangeBorder);
        orangeBorder.setLayout(orangeBorderLayout);
        orangeBorderLayout.setHorizontalGroup(
                orangeBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 10, Short.MAX_VALUE)
        );
        orangeBorderLayout.setVerticalGroup(
                orangeBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        initializer.initializeJButton(jButtonCreate, Main.EIGHTEEN_SEGOE_FONT, "Create project", Main.DARK_GREY, new javax.swing.border.LineBorder(new java.awt.Color(250, 152, 60), 4, true));
        jButtonCreate.setBackground(new java.awt.Color(45, 46, 45));
        jButtonCreate.addActionListener(this::jButtonCreateActionPerformed);

        initializer.initializeJButton(jButtonBack,Main.FORTY_EIGHT_SEGOE_FONT, "«", Main.DARK_GREY, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 152, 60), 4));
        jButtonBack.setBackground(new java.awt.Color(45, 46, 45));
        jButtonBack.addActionListener(evt -> jButtonBackActionPerformed());

        jTextFieldName.setBackground(new java.awt.Color(87, 89, 87));
        jTextFieldName.setForeground(new java.awt.Color(45, 46, 45));
        jTextFieldName.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        initializer.initializeLabels(jLabelPageTitle, Main.TV_POSTER_FONT, "Insert the data of your project", SwingConstants.CENTER, Main.LIGHT_BLUE);

        initializer.initializeLabels(jLabelPName, Main.TWELVE_SEGOE_FONT, "PROJECT NAME:", SwingConstants.RIGHT, Main.DARK_BLUE);
        initializer.initializeLabels(jLabelPDesc, Main.TWELVE_SEGOE_FONT, "DESCRIPTION:", SwingConstants.RIGHT, Main.DARK_BLUE);

        jTextFieldDescription.setBackground(new java.awt.Color(87, 89, 87));
        jTextFieldDescription.setForeground(new java.awt.Color(45, 46, 45));
        jTextFieldDescription.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        initializer.initializeJButton(jButtonRoad, Main.FOURTEEN_SEGOE_FONT, "Import roads configuration file", Color.WHITE, new javax.swing.border.LineBorder(new java.awt.Color(155, 177, 189), 2, true));
        jButtonRoad.setBackground(new java.awt.Color(45, 46, 45));
        jButtonRoad.addActionListener(evt -> jButtonRoadActionPerformed());

        initializer.initializeJButton(jButtonVehicle, Main.FOURTEEN_SEGOE_FONT, "Import vehicles configuration file", Color.WHITE, new javax.swing.border.LineBorder(new java.awt.Color(155, 177, 189), 2, true));
        jButtonVehicle.setBackground(new java.awt.Color(45, 46, 45));
        jButtonVehicle.addActionListener(evt -> jButtonVehicleActionPerformed());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(imgLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(orangeBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addComponent(jButtonVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonRoad, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabelPName)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(28, 28, 28))
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jLabelPDesc)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(jTextFieldDescription, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jButtonCreate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(100, 100, 100)
                                                .addComponent(jLabelPageTitle)))
                                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(orangeBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(imgLateral)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabelPageTitle)
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelPName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelPDesc))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonRoad)
                                        .addComponent(jButtonVehicle))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateActionPerformed
        if (jTextFieldName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insert a Name for your project");
        } else if (jTextFieldDescription.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insert a Description for your project");
        } else if (createProjectController.getRoadsFile() == null) {
            JOptionPane.showMessageDialog(null, "Import the File that contains the Roads in your project");
        } else if (createProjectController.getVehiclesFile() == null) {
            JOptionPane.showMessageDialog(null, "Import the File that contains the Vehicles in your project");
        } else {
            try {
                createProjectController.createProject(jTextFieldName.getText(), jTextFieldDescription.getText());
                JOptionPane.showMessageDialog(this, "Project created.");
            } catch (Exception ex) {
                Logger.getLogger(CreateProjectUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonCreateActionPerformed

    private void jButtonBackActionPerformed() {//GEN-FIRST:event_jButtonBackActionPerformed
        WelcomeUI.display();
        dispose();
    }

    private void jButtonRoadActionPerformed() {//GEN-FIRST:event_jButtonRoadActionPerformed
        Main.SupportedInputFileTypes selectedExtension = Main.displayExtensionChoiceUI(null);
        JFileChooser fileChooser = Main.initFileChooserProperties(selectedExtension, "Select your RoadNetwork file");
        loadFile(fileChooser, jButtonRoad, createProjectController::setRoadNetworkFile, selectedExtension);
    }


    private void jButtonVehicleActionPerformed() {//GEN-FIRST:event_jButtonVehicleActionPerformed
        Main.SupportedInputFileTypes selectedExtension = Main.displayExtensionChoiceUI(null);
        JFileChooser fileChooser = Main.initFileChooserProperties(selectedExtension, "Select your Vehicles file");
        loadFile(fileChooser, jButtonVehicle, createProjectController::setVehiclesFile, selectedExtension);
    }

    /**
     * Loads a file, executing the action designated by the {@code action} {@link Consumer}
     */
    private void loadFile(JFileChooser fileChooser, JButton attachedButton, Consumer<File> action, Main.SupportedInputFileTypes extension) {
        int returnVal = fileChooser.showOpenDialog(attachedButton);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            action.accept(selectedFile);
            createProjectController.setExtensionParsingMode(extension);
            JOptionPane.showMessageDialog(null, "Your file has been loaded.");
        }
    }

    /**
     * Triggers UI display
     */
    public static void display() {
        Main.setLook();
        java.awt.EventQueue.invokeLater(() -> new CreateProjectUI().setVisible(true));
    }

}
