/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lapr.project.ui;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import lapr.project.controller.CopyProjectController;

import static lapr.project.ui.Main.dbCom;

/**
 * @author anily
 */
class PopUp1 extends javax.swing.JFrame {

    private static final long serialVersionUID = 8060730009198569465L;
    private SelectProjectUI selectProjectUI;

    /**
     * Creates new form PopUp1
     */
    PopUp1(SelectProjectUI selectProjectUI) {
        this.selectProjectUI = selectProjectUI;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgLateral = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonChangeData = new javax.swing.JButton();
        jButtonCopy = new javax.swing.JButton();
        imgLateral1 = new javax.swing.JLabel();
        InitializeUIElements initializer = new InitializeUIElements();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imgLateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fundo.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(155, 177, 189));

        initializer.initializeJButton(jButtonChangeData, Main.EIGHTEEN_SEGOE_FONT, "Change project data", Main.DARK_GREY, new javax.swing.border.LineBorder(new java.awt.Color(250, 152, 60), 4, true));
        jButtonChangeData.setBackground(new java.awt.Color(45, 46, 45));
        jButtonChangeData.addActionListener(evt -> jButtonChangeDataActionPerformed(evt));

        initializer.initializeJButton(jButtonChangeData, Main.EIGHTEEN_SEGOE_FONT, "Copy project", Main.DARK_GREY, new javax.swing.border.LineBorder(new java.awt.Color(250, 152, 60), 4, true));
        jButtonCopy.setBackground(new java.awt.Color(45, 46, 45));
        jButtonCopy.addActionListener(evt -> jButtonCopyActionPerformed(evt));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonChangeData, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jButtonChangeData, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(39, Short.MAX_VALUE))
        );

        imgLateral1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fundo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(imgLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imgLateral1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(imgLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imgLateral1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonChangeDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeDataActionPerformed
        ChangeDataUI.display();
        selectProjectUI.dispose();
        dispose();
    }//GEN-LAST:event_jButtonChangeDataActionPerformed

    private void jButtonCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCopyActionPerformed

        CopyProjectController copyProjectController = new CopyProjectController(dbCom);

        try {
            if (!copyProjectController.cloneProject(Main.currentProject)) {
                JOptionPane.showMessageDialog(
                        this,
                        "It's not possible to copy the actual project!",
                        "Copy Project",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                copyProjectController.cloneProject(Main.currentProject);
                JOptionPane.showMessageDialog(
                        this,
                        "The current project, " + Main.currentProject.getName()
                                + ", was cloned and stored successfully!",
                        "Copy Project",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (CloneNotSupportedException ex) {
            Logger.getLogger(SelectProjectUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCopyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgLateral;
    private javax.swing.JLabel imgLateral1;
    private javax.swing.JButton jButtonChangeData;
    private javax.swing.JButton jButtonCopy;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
